###########################################################
#  COMMON SETTINGS                                        #
###########################################################
 debug_mode: false

###########################################################
# APPLICATION SETTINGS                                    #
###########################################################
 app_base_auth_login:
 app_base_auth_pass:
 app_protocol: http
 app_host: hagal.theadventus.com/AbbottPlate/
 app_url:  ${app_protocol}://${app_host}
 
 abbottplate_support_email: e_mail126rjw@126.com

 def_test_user: test@test.com
 def_test_pass: mypass
 def_test_name: Auto Tester

###########################################################
# TEST ENVIRONMENTS SETTINGS                              #
###########################################################

 # Specify one of the following drivers: selenium, selenium_dev, webkit, poltergeist, phantomjs, sauce, testingbot
 driver: poltergeist

 # -Selenium-
 # specify one of next browsers: iexplore (ie), firefox (ff), chrome, opera
 sel_browser: phantomjs

 # -PhantomJS-
 # specify settings for poltergeist
 pjs_ignore_js_errors: true
 pjs_ignore_ssl_errors: true

 # -SauceLabs-
 sl_user: some_user
 sl_api_key: some_api_key
 sl_url: "http://${sl_user}:${sl_api_key}@ondemand.saucelabs.com:80/wd/hub"
 sl_platform: :VISTA
 sl_browser_name: firefox
 sl_selenium_version: "2.18.0"
 sl_max_duration: '1800'
 sl_idle_timeout: '180'

 # -TestingBot- browsers that are supported: firefox => '8', googlechrome, iexplore => '9'
 tb_api_key: client_key
 tb_api_secret: client_secret
 tb_url: "http://${tb_api_key}:${tb_api_secret}@hub.testingbot.com:80/wd/hub"
 tb_platform: :WIN8
 tb_browser_name: firefox
 tb_browser_version: 8
 tb_selenium_version: "2.18.0"
 tb_max_duration: '1800'
 tb_idle_timeout: '180'
 tb_record_screenshot: false

###########################################################
# DATABASE SETTINGS                                       #
###########################################################
 ss_save_folder: abplate_testing_script/failed_tests_ss


###########################################################
# LOGGER SETTINGS                                         #
###########################################################
 log_dir: "log"
 txt_log: log.txt
 html_log: log.html
 selenium_server_log: selenium-server.log
 required_clean_logs: true
 rawler_log: rawler_log.txt
 add_rawler_xml_log: false
 rawler_xml_log: rawler_log.xml
 add_rawler_html_log: false # not implemented yet
 rawler_html_log: rawler_log.html # not implemented yet

###########################################################
# MAILGUN SETTINGS                                        #
###########################################################
 #mailgun_key: mailgun_account_private_key
 #mailgun_domain: mailgun_domain_with_stored_method

 mailgun_key: key-01b026be91b3d14cd57238e35ea79501
 mailgun_domain: sandboxcafca03671284fe5aedbcabf20df1737.mailgun.org

############################################################
# TIMEOUTS                                                 #
############################################################
 timeout_tiny: 2
 timeout_short: 6
 timeout_small: 40
 timeout_medium: 60

